apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1 # Three backend instances
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bookstore-backend:latest # Backend Docker image
        imagePullPolicy: Never
        ports:
        - containerPort: 5001 #Current port open
        env:
        - name: MONGO_URI
          value: "mongodb+srv://dbuser:dbpassword@clusterlibreria.wxzq4.mongodb.net/db_library?retryWrites=true&w=majority&appName=clusterLibreria"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
